[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
name = "aldyparen-py"
version = "3.2.0"
description = "Renders pictures and videos of algebraic fractals"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT" 
authors = [{ name = "Dima Fedoriaka" }]

# https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Multimedia :: Graphics",
]

# https://peps.python.org/pep-0508/
dependencies = [
    "matplotlib>=3.7.1",
    "moviepy>=2.2.1",
    "numba>=0.67",
    "numpy>=2.5",
    "PyQt5>=5.15.9",
]

# Development dependencies
# pip install .[lint,test,dev]
[project.optional-dependencies]
lint = [
    "black==25.1.0",
    "pyright==1.1.411",
]
test = [
    "pytest>=8.4.0",
]
dev = [
    "coverage",
]

[project.urls]
"Homepage" = "https://github.com/fedimser/aldyparen-py"

[tool.setuptools.packages.find]
where = ["."]
include = ["aldyparen*"]

[tool.black]
line-length = 120
